Turtle:
  base_controller:
    type         : "diff_drive_controller/DiffDriveController" 
    left_wheel   : 'WHEEL_L'
    right_wheel  : 'WHEEL_R'
    publish_rate : 50
    pose_covariance_diagonal  : [ 0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0 ]
    twist_covariance_diagonal : [ 0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0 ]
    wheel_separation : 0.16
    wheel_radius : 0.033
    wheel_separation_multiplier: 1.0
    wheel_radius_multiplier    : 1.0
    cmd_vel_timeout : 1.0
    enable_odom_tf  : true
    linear:
      x:
        has_velocity_limits     : true
        #max_velocity            :  4.0 # m/s
        #min_velocity            : -4.0 # m/s
        max_velocity            :  0.18 # m/s
        min_velocity            : -0.08 # m/s
        has_acceleration_limits : true
        max_acceleration        :  0.5 # m/s^2
        min_acceleration        : -0.5 # m/s^2
    angular:
      z:
        haz_velocity_limits     : true
        #max_velocity            :  6.28 # rad/s
        #min_velocity            : -6.28 # rad/s
        max_velocity            :  0.30 # rad/s
        min_velocity            : -0.30 # rad/s
        has_acceleration_limits : true
        max_acceleration        :  0.785 # rad/s^2
        min_acceleration        : -0.785 # rad/s^2
